# ----------------------------------------------------------------------------------------------------------------------
# System Config
# Default Select: Windows 509 and Linux 1024, windows <= 64
# ----------------------------------------------------------------------------------------------------------------------
[general]
depth = 1
threads = 300
asyncio = 50

[network]
headers = {}

[notice]
enable = false
username = ""
password = ""
host = ""
send = ""

# ----------------------------------------------------------------------------------------------------------------------
# Plugin Config
# ----------------------------------------------------------------------------------------------------------------------

[cmd5]
email = ""
key = ""
link = "https://www.cmd5.com"

[ipinfo]
key = ""
link = "http://ipinfo.io"

[hunter]
key = ""
link = "https://api.hunter.io"

[virustotal]
key = ""
link = "https://www.virustotal.com"

[circl]
user = ""
pwd = ""
link = "https://www.circl.lu"

[censys]
api_id = ""
secret = ""
link = "https://censys.io"

[whoisxmlapi]
key = ""
link = "https://subdomains.whoisxmlapi.com"

[securitytrails]
key = ""
link = "https://securitytrails.com"

[aiqicha]
# ua与cookie绑定 需要一同复制过来
ua = ""
cookie = ""
link = "https://aiqicha.baidu.com"

[zoomeye]
key = ""
link = "https://zoomeye.org"


