# ----------------------------------------------------------------------------------------------------------------------
# System Config
# Default Select: Windows 509 and Linux 1024
# ----------------------------------------------------------------------------------------------------------------------
[general]
depth = 2
threads = 300
asyncio = 150

[notice]
enable = false
username = ""
password = ""
host = ""
send = ""

# ----------------------------------------------------------------------------------------------------------------------
# Plugin Config
# ----------------------------------------------------------------------------------------------------------------------

[cmd5]
email = ""
key = ""
link = "https://www.cmd5.com"

[ipinfo]
key = ""
link = "http://ipinfo.io"
