# ----------------------------------------------------------------------------------------------------------------------
# System Config
# Default Select: Windows 509 and Linux 1024, windows <= 64
# ----------------------------------------------------------------------------------------------------------------------
[general]
version = "1.4.9"
depth = 1
threads = 100
asyncio = 50

# ----------------------------------------------------------------------------------------------------------------------
# Network Config
# ----------------------------------------------------------------------------------------------------------------------

[network]
    [network.headers]
        "User-Agent" = "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.127 Safari/537.36 Edg/100.0.1185.44"
        "Content-Type" = "application/x-www-form-urlencoded"
        "Referer" = "https://www.google.com"
    [network.proxies]
        http = ""
        https = ""

# ----------------------------------------------------------------------------------------------------------------------
# Plugin Config
# ----------------------------------------------------------------------------------------------------------------------

[cmd5]
email = ""
key = ""
link = "https://www.cmd5.com"

[ipinfo]
key = ""
link = "http://ipinfo.io"

[hunter]
key = ""
link = "https://api.hunter.io"

[virustotal]
key = ""
link = "https://www.virustotal.com"

[circl]
user = ""
pwd = ""
link = "https://www.circl.lu"

[censys]
api_id = ""
secret = ""
link = "https://censys.io"

[whoisxmlapi]
key = ""
link = "https://subdomains.whoisxmlapi.com"

[securitytrails]
key = ""
link = "https://securitytrails.com"

[aiqicha]
# ua与cookie绑定 需要一同复制过来
ua = ""
cookie = ""
link = "https://aiqicha.baidu.com"

[zoomeye]
key = ""
link = "https://zoomeye.org"

[fofa]
key = ""
email = ""
link = "https://fofa.info"

